spring.application.name=url-shortner
server.port=8080
app.domain=http://localhost:8080/

# Database (H2 In-Memory Default)
spring.datasource.url=jdbc:h2:mem:urldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Caching (Caffeine L1)
spring.cache.type=caffeine
spring.cache.cache-names=urlCache,qrCache
spring.cache.caffeine.spec=maximumSize=10000,expireAfterWrite=60m

# H2 Console for verification
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator Health Checks (Disable Redis locally)
management.health.redis.enabled=false

